const MOCK_DATA = {
	total_count: 140388,
	incomplete_results: false,
	items: [
		{
			login: 'java',
			id: 6456,
			node_id: 'MDQ6VXNlcjY0NTY=',
			avatar_url: 'https://avatars.githubusercontent.com/u/6456?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/java',
			html_url: 'https://github.com/java',
			followers_url: 'https://api.github.com/users/java/followers',
			following_url: 'https://api.github.com/users/java/following{/other_user}',
			gists_url: 'https://api.github.com/users/java/gists{/gist_id}',
			starred_url: 'https://api.github.com/users/java/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/java/subscriptions',
			organizations_url: 'https://api.github.com/users/java/orgs',
			repos_url: 'https://api.github.com/users/java/repos',
			events_url: 'https://api.github.com/users/java/events{/privacy}',
			received_events_url: 'https://api.github.com/users/java/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'xiaoshi316',
			id: 11763933,
			node_id: 'MDQ6VXNlcjExNzYzOTMz',
			avatar_url: 'https://avatars.githubusercontent.com/u/11763933?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/xiaoshi316',
			html_url: 'https://github.com/xiaoshi316',
			followers_url: 'https://api.github.com/users/xiaoshi316/followers',
			following_url:
				'https://api.github.com/users/xiaoshi316/following{/other_user}',
			gists_url: 'https://api.github.com/users/xiaoshi316/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/xiaoshi316/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/xiaoshi316/subscriptions',
			organizations_url: 'https://api.github.com/users/xiaoshi316/orgs',
			repos_url: 'https://api.github.com/users/xiaoshi316/repos',
			events_url: 'https://api.github.com/users/xiaoshi316/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/xiaoshi316/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'RicardoToledoB',
			id: 1168968,
			node_id: 'MDQ6VXNlcjExNjg5Njg=',
			avatar_url: 'https://avatars.githubusercontent.com/u/1168968?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/RicardoToledoB',
			html_url: 'https://github.com/RicardoToledoB',
			followers_url: 'https://api.github.com/users/RicardoToledoB/followers',
			following_url:
				'https://api.github.com/users/RicardoToledoB/following{/other_user}',
			gists_url: 'https://api.github.com/users/RicardoToledoB/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/RicardoToledoB/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/RicardoToledoB/subscriptions',
			organizations_url: 'https://api.github.com/users/RicardoToledoB/orgs',
			repos_url: 'https://api.github.com/users/RicardoToledoB/repos',
			events_url:
				'https://api.github.com/users/RicardoToledoB/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/RicardoToledoB/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'javayhu',
			id: 1982582,
			node_id: 'MDQ6VXNlcjE5ODI1ODI=',
			avatar_url: 'https://avatars.githubusercontent.com/u/1982582?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/javayhu',
			html_url: 'https://github.com/javayhu',
			followers_url: 'https://api.github.com/users/javayhu/followers',
			following_url:
				'https://api.github.com/users/javayhu/following{/other_user}',
			gists_url: 'https://api.github.com/users/javayhu/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/javayhu/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/javayhu/subscriptions',
			organizations_url: 'https://api.github.com/users/javayhu/orgs',
			repos_url: 'https://api.github.com/users/javayhu/repos',
			events_url: 'https://api.github.com/users/javayhu/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/javayhu/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'javahometech',
			id: 16301058,
			node_id: 'MDQ6VXNlcjE2MzAxMDU4',
			avatar_url: 'https://avatars.githubusercontent.com/u/16301058?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/javahometech',
			html_url: 'https://github.com/javahometech',
			followers_url: 'https://api.github.com/users/javahometech/followers',
			following_url:
				'https://api.github.com/users/javahometech/following{/other_user}',
			gists_url: 'https://api.github.com/users/javahometech/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/javahometech/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/javahometech/subscriptions',
			organizations_url: 'https://api.github.com/users/javahometech/orgs',
			repos_url: 'https://api.github.com/users/javahometech/repos',
			events_url: 'https://api.github.com/users/javahometech/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/javahometech/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'javan',
			id: 5355,
			node_id: 'MDQ6VXNlcjUzNTU=',
			avatar_url: 'https://avatars.githubusercontent.com/u/5355?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/javan',
			html_url: 'https://github.com/javan',
			followers_url: 'https://api.github.com/users/javan/followers',
			following_url:
				'https://api.github.com/users/javan/following{/other_user}',
			gists_url: 'https://api.github.com/users/javan/gists{/gist_id}',
			starred_url: 'https://api.github.com/users/javan/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/javan/subscriptions',
			organizations_url: 'https://api.github.com/users/javan/orgs',
			repos_url: 'https://api.github.com/users/javan/repos',
			events_url: 'https://api.github.com/users/javan/events{/privacy}',
			received_events_url: 'https://api.github.com/users/javan/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'javascriptual',
			id: 4739311,
			node_id: 'MDQ6VXNlcjQ3MzkzMTE=',
			avatar_url: 'https://avatars.githubusercontent.com/u/4739311?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/javascriptual',
			html_url: 'https://github.com/javascriptual',
			followers_url: 'https://api.github.com/users/javascriptual/followers',
			following_url:
				'https://api.github.com/users/javascriptual/following{/other_user}',
			gists_url: 'https://api.github.com/users/javascriptual/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/javascriptual/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/javascriptual/subscriptions',
			organizations_url: 'https://api.github.com/users/javascriptual/orgs',
			repos_url: 'https://api.github.com/users/javascriptual/repos',
			events_url: 'https://api.github.com/users/javascriptual/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/javascriptual/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'javajigi',
			id: 520500,
			node_id: 'MDQ6VXNlcjUyMDUwMA==',
			avatar_url: 'https://avatars.githubusercontent.com/u/520500?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/javajigi',
			html_url: 'https://github.com/javajigi',
			followers_url: 'https://api.github.com/users/javajigi/followers',
			following_url:
				'https://api.github.com/users/javajigi/following{/other_user}',
			gists_url: 'https://api.github.com/users/javajigi/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/javajigi/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/javajigi/subscriptions',
			organizations_url: 'https://api.github.com/users/javajigi/orgs',
			repos_url: 'https://api.github.com/users/javajigi/repos',
			events_url: 'https://api.github.com/users/javajigi/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/javajigi/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'Java-Edge',
			id: 24735696,
			node_id: 'MDQ6VXNlcjI0NzM1Njk2',
			avatar_url: 'https://avatars.githubusercontent.com/u/24735696?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/Java-Edge',
			html_url: 'https://github.com/Java-Edge',
			followers_url: 'https://api.github.com/users/Java-Edge/followers',
			following_url:
				'https://api.github.com/users/Java-Edge/following{/other_user}',
			gists_url: 'https://api.github.com/users/Java-Edge/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/Java-Edge/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/Java-Edge/subscriptions',
			organizations_url: 'https://api.github.com/users/Java-Edge/orgs',
			repos_url: 'https://api.github.com/users/Java-Edge/repos',
			events_url: 'https://api.github.com/users/Java-Edge/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/Java-Edge/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'javabyraghu',
			id: 15054479,
			node_id: 'MDQ6VXNlcjE1MDU0NDc5',
			avatar_url: 'https://avatars.githubusercontent.com/u/15054479?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/javabyraghu',
			html_url: 'https://github.com/javabyraghu',
			followers_url: 'https://api.github.com/users/javabyraghu/followers',
			following_url:
				'https://api.github.com/users/javabyraghu/following{/other_user}',
			gists_url: 'https://api.github.com/users/javabyraghu/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/javabyraghu/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/javabyraghu/subscriptions',
			organizations_url: 'https://api.github.com/users/javabyraghu/orgs',
			repos_url: 'https://api.github.com/users/javabyraghu/repos',
			events_url: 'https://api.github.com/users/javabyraghu/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/javabyraghu/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'javadev',
			id: 348496,
			node_id: 'MDQ6VXNlcjM0ODQ5Ng==',
			avatar_url: 'https://avatars.githubusercontent.com/u/348496?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/javadev',
			html_url: 'https://github.com/javadev',
			followers_url: 'https://api.github.com/users/javadev/followers',
			following_url:
				'https://api.github.com/users/javadev/following{/other_user}',
			gists_url: 'https://api.github.com/users/javadev/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/javadev/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/javadev/subscriptions',
			organizations_url: 'https://api.github.com/users/javadev/orgs',
			repos_url: 'https://api.github.com/users/javadev/repos',
			events_url: 'https://api.github.com/users/javadev/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/javadev/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'javascripter',
			id: 13040,
			node_id: 'MDQ6VXNlcjEzMDQw',
			avatar_url: 'https://avatars.githubusercontent.com/u/13040?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/javascripter',
			html_url: 'https://github.com/javascripter',
			followers_url: 'https://api.github.com/users/javascripter/followers',
			following_url:
				'https://api.github.com/users/javascripter/following{/other_user}',
			gists_url: 'https://api.github.com/users/javascripter/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/javascripter/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/javascripter/subscriptions',
			organizations_url: 'https://api.github.com/users/javascripter/orgs',
			repos_url: 'https://api.github.com/users/javascripter/repos',
			events_url: 'https://api.github.com/users/javascripter/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/javascripter/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'JavaFXpert',
			id: 9936602,
			node_id: 'MDQ6VXNlcjk5MzY2MDI=',
			avatar_url: 'https://avatars.githubusercontent.com/u/9936602?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/JavaFXpert',
			html_url: 'https://github.com/JavaFXpert',
			followers_url: 'https://api.github.com/users/JavaFXpert/followers',
			following_url:
				'https://api.github.com/users/JavaFXpert/following{/other_user}',
			gists_url: 'https://api.github.com/users/JavaFXpert/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/JavaFXpert/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/JavaFXpert/subscriptions',
			organizations_url: 'https://api.github.com/users/JavaFXpert/orgs',
			repos_url: 'https://api.github.com/users/JavaFXpert/repos',
			events_url: 'https://api.github.com/users/JavaFXpert/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/JavaFXpert/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'Java0Tutor',
			id: 50914641,
			node_id: 'MDQ6VXNlcjUwOTE0NjQx',
			avatar_url: 'https://avatars.githubusercontent.com/u/50914641?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/Java0Tutor',
			html_url: 'https://github.com/Java0Tutor',
			followers_url: 'https://api.github.com/users/Java0Tutor/followers',
			following_url:
				'https://api.github.com/users/Java0Tutor/following{/other_user}',
			gists_url: 'https://api.github.com/users/Java0Tutor/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/Java0Tutor/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/Java0Tutor/subscriptions',
			organizations_url: 'https://api.github.com/users/Java0Tutor/orgs',
			repos_url: 'https://api.github.com/users/Java0Tutor/repos',
			events_url: 'https://api.github.com/users/Java0Tutor/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/Java0Tutor/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'charliecalvert',
			id: 1811478,
			node_id: 'MDQ6VXNlcjE4MTE0Nzg=',
			avatar_url: 'https://avatars.githubusercontent.com/u/1811478?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/charliecalvert',
			html_url: 'https://github.com/charliecalvert',
			followers_url: 'https://api.github.com/users/charliecalvert/followers',
			following_url:
				'https://api.github.com/users/charliecalvert/following{/other_user}',
			gists_url: 'https://api.github.com/users/charliecalvert/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/charliecalvert/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/charliecalvert/subscriptions',
			organizations_url: 'https://api.github.com/users/charliecalvert/orgs',
			repos_url: 'https://api.github.com/users/charliecalvert/repos',
			events_url:
				'https://api.github.com/users/charliecalvert/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/charliecalvert/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'javacasm',
			id: 3841695,
			node_id: 'MDQ6VXNlcjM4NDE2OTU=',
			avatar_url: 'https://avatars.githubusercontent.com/u/3841695?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/javacasm',
			html_url: 'https://github.com/javacasm',
			followers_url: 'https://api.github.com/users/javacasm/followers',
			following_url:
				'https://api.github.com/users/javacasm/following{/other_user}',
			gists_url: 'https://api.github.com/users/javacasm/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/javacasm/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/javacasm/subscriptions',
			organizations_url: 'https://api.github.com/users/javacasm/orgs',
			repos_url: 'https://api.github.com/users/javacasm/repos',
			events_url: 'https://api.github.com/users/javacasm/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/javacasm/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'holajiawei',
			id: 31928088,
			node_id: 'MDQ6VXNlcjMxOTI4MDg4',
			avatar_url: 'https://avatars.githubusercontent.com/u/31928088?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/holajiawei',
			html_url: 'https://github.com/holajiawei',
			followers_url: 'https://api.github.com/users/holajiawei/followers',
			following_url:
				'https://api.github.com/users/holajiawei/following{/other_user}',
			gists_url: 'https://api.github.com/users/holajiawei/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/holajiawei/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/holajiawei/subscriptions',
			organizations_url: 'https://api.github.com/users/holajiawei/orgs',
			repos_url: 'https://api.github.com/users/holajiawei/repos',
			events_url: 'https://api.github.com/users/holajiawei/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/holajiawei/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'java-aodeng',
			id: 35907367,
			node_id: 'MDQ6VXNlcjM1OTA3MzY3',
			avatar_url: 'https://avatars.githubusercontent.com/u/35907367?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/java-aodeng',
			html_url: 'https://github.com/java-aodeng',
			followers_url: 'https://api.github.com/users/java-aodeng/followers',
			following_url:
				'https://api.github.com/users/java-aodeng/following{/other_user}',
			gists_url: 'https://api.github.com/users/java-aodeng/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/java-aodeng/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/java-aodeng/subscriptions',
			organizations_url: 'https://api.github.com/users/java-aodeng/orgs',
			repos_url: 'https://api.github.com/users/java-aodeng/repos',
			events_url: 'https://api.github.com/users/java-aodeng/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/java-aodeng/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'javache',
			id: 5676,
			node_id: 'MDQ6VXNlcjU2NzY=',
			avatar_url: 'https://avatars.githubusercontent.com/u/5676?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/javache',
			html_url: 'https://github.com/javache',
			followers_url: 'https://api.github.com/users/javache/followers',
			following_url:
				'https://api.github.com/users/javache/following{/other_user}',
			gists_url: 'https://api.github.com/users/javache/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/javache/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/javache/subscriptions',
			organizations_url: 'https://api.github.com/users/javache/orgs',
			repos_url: 'https://api.github.com/users/javache/repos',
			events_url: 'https://api.github.com/users/javache/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/javache/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'javalangClass',
			id: 14233310,
			node_id: 'MDQ6VXNlcjE0MjMzMzEw',
			avatar_url: 'https://avatars.githubusercontent.com/u/14233310?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/javalangClass',
			html_url: 'https://github.com/javalangClass',
			followers_url: 'https://api.github.com/users/javalangClass/followers',
			following_url:
				'https://api.github.com/users/javalangClass/following{/other_user}',
			gists_url: 'https://api.github.com/users/javalangClass/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/javalangClass/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/javalangClass/subscriptions',
			organizations_url: 'https://api.github.com/users/javalangClass/orgs',
			repos_url: 'https://api.github.com/users/javalangClass/repos',
			events_url: 'https://api.github.com/users/javalangClass/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/javalangClass/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'JavaRockstar',
			id: 20056967,
			node_id: 'MDQ6VXNlcjIwMDU2OTY3',
			avatar_url: 'https://avatars.githubusercontent.com/u/20056967?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/JavaRockstar',
			html_url: 'https://github.com/JavaRockstar',
			followers_url: 'https://api.github.com/users/JavaRockstar/followers',
			following_url:
				'https://api.github.com/users/JavaRockstar/following{/other_user}',
			gists_url: 'https://api.github.com/users/JavaRockstar/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/JavaRockstar/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/JavaRockstar/subscriptions',
			organizations_url: 'https://api.github.com/users/JavaRockstar/orgs',
			repos_url: 'https://api.github.com/users/JavaRockstar/repos',
			events_url: 'https://api.github.com/users/JavaRockstar/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/JavaRockstar/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'JavaCodeMood',
			id: 19645978,
			node_id: 'MDQ6VXNlcjE5NjQ1OTc4',
			avatar_url: 'https://avatars.githubusercontent.com/u/19645978?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/JavaCodeMood',
			html_url: 'https://github.com/JavaCodeMood',
			followers_url: 'https://api.github.com/users/JavaCodeMood/followers',
			following_url:
				'https://api.github.com/users/JavaCodeMood/following{/other_user}',
			gists_url: 'https://api.github.com/users/JavaCodeMood/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/JavaCodeMood/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/JavaCodeMood/subscriptions',
			organizations_url: 'https://api.github.com/users/JavaCodeMood/orgs',
			repos_url: 'https://api.github.com/users/JavaCodeMood/repos',
			events_url: 'https://api.github.com/users/JavaCodeMood/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/JavaCodeMood/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'javasoze',
			id: 168714,
			node_id: 'MDQ6VXNlcjE2ODcxNA==',
			avatar_url: 'https://avatars.githubusercontent.com/u/168714?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/javasoze',
			html_url: 'https://github.com/javasoze',
			followers_url: 'https://api.github.com/users/javasoze/followers',
			following_url:
				'https://api.github.com/users/javasoze/following{/other_user}',
			gists_url: 'https://api.github.com/users/javasoze/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/javasoze/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/javasoze/subscriptions',
			organizations_url: 'https://api.github.com/users/javasoze/orgs',
			repos_url: 'https://api.github.com/users/javasoze/repos',
			events_url: 'https://api.github.com/users/javasoze/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/javasoze/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'JavaScriptErika',
			id: 19316487,
			node_id: 'MDQ6VXNlcjE5MzE2NDg3',
			avatar_url: 'https://avatars.githubusercontent.com/u/19316487?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/JavaScriptErika',
			html_url: 'https://github.com/JavaScriptErika',
			followers_url: 'https://api.github.com/users/JavaScriptErika/followers',
			following_url:
				'https://api.github.com/users/JavaScriptErika/following{/other_user}',
			gists_url: 'https://api.github.com/users/JavaScriptErika/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/JavaScriptErika/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/JavaScriptErika/subscriptions',
			organizations_url: 'https://api.github.com/users/JavaScriptErika/orgs',
			repos_url: 'https://api.github.com/users/JavaScriptErika/repos',
			events_url:
				'https://api.github.com/users/JavaScriptErika/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/JavaScriptErika/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'javaguirre',
			id: 488556,
			node_id: 'MDQ6VXNlcjQ4ODU1Ng==',
			avatar_url: 'https://avatars.githubusercontent.com/u/488556?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/javaguirre',
			html_url: 'https://github.com/javaguirre',
			followers_url: 'https://api.github.com/users/javaguirre/followers',
			following_url:
				'https://api.github.com/users/javaguirre/following{/other_user}',
			gists_url: 'https://api.github.com/users/javaguirre/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/javaguirre/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/javaguirre/subscriptions',
			organizations_url: 'https://api.github.com/users/javaguirre/orgs',
			repos_url: 'https://api.github.com/users/javaguirre/repos',
			events_url: 'https://api.github.com/users/javaguirre/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/javaguirre/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'ptteng',
			id: 24518143,
			node_id: 'MDQ6VXNlcjI0NTE4MTQz',
			avatar_url: 'https://avatars.githubusercontent.com/u/24518143?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/ptteng',
			html_url: 'https://github.com/ptteng',
			followers_url: 'https://api.github.com/users/ptteng/followers',
			following_url:
				'https://api.github.com/users/ptteng/following{/other_user}',
			gists_url: 'https://api.github.com/users/ptteng/gists{/gist_id}',
			starred_url: 'https://api.github.com/users/ptteng/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/ptteng/subscriptions',
			organizations_url: 'https://api.github.com/users/ptteng/orgs',
			repos_url: 'https://api.github.com/users/ptteng/repos',
			events_url: 'https://api.github.com/users/ptteng/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/ptteng/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'JavaNoober',
			id: 19897933,
			node_id: 'MDQ6VXNlcjE5ODk3OTMz',
			avatar_url: 'https://avatars.githubusercontent.com/u/19897933?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/JavaNoober',
			html_url: 'https://github.com/JavaNoober',
			followers_url: 'https://api.github.com/users/JavaNoober/followers',
			following_url:
				'https://api.github.com/users/JavaNoober/following{/other_user}',
			gists_url: 'https://api.github.com/users/JavaNoober/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/JavaNoober/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/JavaNoober/subscriptions',
			organizations_url: 'https://api.github.com/users/JavaNoober/orgs',
			repos_url: 'https://api.github.com/users/JavaNoober/repos',
			events_url: 'https://api.github.com/users/JavaNoober/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/JavaNoober/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'javaturk',
			id: 6938846,
			node_id: 'MDQ6VXNlcjY5Mzg4NDY=',
			avatar_url: 'https://avatars.githubusercontent.com/u/6938846?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/javaturk',
			html_url: 'https://github.com/javaturk',
			followers_url: 'https://api.github.com/users/javaturk/followers',
			following_url:
				'https://api.github.com/users/javaturk/following{/other_user}',
			gists_url: 'https://api.github.com/users/javaturk/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/javaturk/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/javaturk/subscriptions',
			organizations_url: 'https://api.github.com/users/javaturk/orgs',
			repos_url: 'https://api.github.com/users/javaturk/repos',
			events_url: 'https://api.github.com/users/javaturk/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/javaturk/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'javafa',
			id: 22068177,
			node_id: 'MDQ6VXNlcjIyMDY4MTc3',
			avatar_url: 'https://avatars.githubusercontent.com/u/22068177?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/javafa',
			html_url: 'https://github.com/javafa',
			followers_url: 'https://api.github.com/users/javafa/followers',
			following_url:
				'https://api.github.com/users/javafa/following{/other_user}',
			gists_url: 'https://api.github.com/users/javafa/gists{/gist_id}',
			starred_url: 'https://api.github.com/users/javafa/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/javafa/subscriptions',
			organizations_url: 'https://api.github.com/users/javafa/orgs',
			repos_url: 'https://api.github.com/users/javafa/repos',
			events_url: 'https://api.github.com/users/javafa/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/javafa/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
		{
			login: 'javahongxi',
			id: 8650304,
			node_id: 'MDQ6VXNlcjg2NTAzMDQ=',
			avatar_url: 'https://avatars.githubusercontent.com/u/8650304?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/javahongxi',
			html_url: 'https://github.com/javahongxi',
			followers_url: 'https://api.github.com/users/javahongxi/followers',
			following_url:
				'https://api.github.com/users/javahongxi/following{/other_user}',
			gists_url: 'https://api.github.com/users/javahongxi/gists{/gist_id}',
			starred_url:
				'https://api.github.com/users/javahongxi/starred{/owner}{/repo}',
			subscriptions_url:
				'https://api.github.com/users/javahongxi/subscriptions',
			organizations_url: 'https://api.github.com/users/javahongxi/orgs',
			repos_url: 'https://api.github.com/users/javahongxi/repos',
			events_url: 'https://api.github.com/users/javahongxi/events{/privacy}',
			received_events_url:
				'https://api.github.com/users/javahongxi/received_events',
			type: 'User',
			site_admin: false,
			score: 1.0,
		},
	],
};

export default MOCK_DATA;
